#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Thu Mar 29 09:56:25 2012

import os
import sys

import wx
import Image

# begin wxGlade: extracode
# end wxGlade


class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        """
        <File>
            1. New
            2. Exit
        """
        self.frame_2_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        menuNew = wxglade_tmp_menu.Append(
                        wx.NewId(), "&New", "", wx.ITEM_NORMAL)
        menuExit = wxglade_tmp_menu.Append(
                        wx.NewId(), "&Exit", "", wx.ITEM_NORMAL)
        self.frame_2_menubar.Append(wxglade_tmp_menu, "&File")

        """ Menu: Options
            1. Show Dir
            2. Show image
        """
        wxglade_tmp_menu = wx.Menu()
        menuShowDir = wxglade_tmp_menu.Append(
                        wx.NewId(), "Show &dir", "", wx.ITEM_NORMAL)
        menuShowImage = wxglade_tmp_menu.Append(
                        wx.NewId(), "Show &image", "", wx.ITEM_NORMAL)
        self.frame_2_menubar.Append(wxglade_tmp_menu, "&Options")
        self.SetMenuBar(self.frame_2_menubar)
        # Menu Bar end

        # Status Bar
        self.frame_2_statusbar = self.CreateStatusBar(1, 0)
        # Status Bar end

        # config
        self.__set_properties()
        self.__do_layout()

        """ Bind """
        self.Bind(wx.EVT_MENU, self.OnNew, menuNew)
        self.Bind(wx.EVT_MENU, self.OnExit, menuExit)
        self.Bind(wx.EVT_MENU, self.show_dir, menuShowDir)
        self.Bind(wx.EVT_MENU, self.show_image, menuShowImage)

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("Frame with notebook")
        self.frame_2_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_2_statusbar_fields = ["Creadted with wxGlade!"]
        for i in range(len(frame_2_statusbar_fields)):
            self.frame_2_statusbar.SetStatusText(frame_2_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnNew(self, event):
        print "OnNew()"

    #//OnNew()

    def OnExit(self, e):
        self.Close(True)
    #//OnExit()

    def show_dir(self, event):
        os.system("dir")
    #//show_dir()

    def show_image(self, event):
        im = Image.open("MA330371.JPG")
        im.show()
    #//show_dir()

# end of class MyFrame1
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_2 = MyFrame1(None, -1, "")
    app.SetTopWindow(frame_2)
    frame_2.Show()
    app.MainLoop()
